### ISSUE TITLE
Can I load offline tokenizers in it?

### ISSUE THREAD

**Issue by a136214808** [chonkie-ai/chonkie#23]
I want to load offline gpt2, however it can't load directly, so did I do something wrong?

code:
from autotiktokenizer import AutoTikTokenizer
tokenizer = AutoTikTokenizer.from_pretrained("home/xxx/gpt2")

Error:
HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'home/xxx/gpt2'. Use `repo_type` argument if needed.

**Comment by bhavnicksm** [comment]
Hey @a136214808!

Yes, you should ideally be able to use an offline tokenizer, but the [AutoTikTokenizer](https://github.com/bhavnicksm/autotiktokenizer) repository doesn't yet support this. I'll add this to the issues on AutoTikTokenizer. 

For now, if you are using `gpt2` itself, I would suggest using tiktoken tokenizer directly or passing in the string "gpt2" to the chunker you are using and letting it initialise the optimal tokenizer.

``` python
import tiktoken

tokenizer = tiktoken.get_encoding("gpt2")
```

```python
from chonkie import TokenChunker

chunker = TokenChunker(tokenizer="gpt2")
```

**Comment by bhavnicksm** [comment]
Mentioning the Issue on AutoTikTokenizer here for tracking:  [issue](https://github.com/bhavnicksm/autotiktokenizer/issues/10#issue-2651242678)

**Comment by bhavnicksm** [comment]
Closing this issue since it has been resolved!

Please re-open if you're still facing the issue, thanks 😊
