### ISSUE TITLE
[BUG] EmbeddingsRegistry custom tokenizer does not work

### ISSUE THREAD

**Issue by rsharma-autessa** [chonkie-ai/chonkie#64]
**Describe the bug**
Making a custom model with a callable tokenizer still goes to else statement

**Fix**
https://github.com/bhavnicksm/chonkie/blob/main/src/chonkie/chunker/base.py#L41-L51
Change the if to elif statement at line 45

**To Reproduce**
Create a custom embedding model with a callable tokenizer function

**Expected behavior**
When I create a new BaseModel, it uses my custom callable tokenizer function

**Additional context**
When I tested with the code change things just work, and based on docstring it looks like that's the ideal behavior.

**Comment by rsharma-autessa** [comment]
Thank YOU so much for the library!


You could try something like this:

```python
class CustomEmebeddings(BaseEmbeddings):
    def __init__(self, model_name: str):
        super().__init__()
        self.model_name = model_name

    def embed(self, text: str) -> "np.ndarray":
        return np.array([1.0, 2.0])

    def embed_batch(self, texts: List[str]) -> List["np.ndarray"]:
        return [self.embed(text) for text in texts]

    def count_tokens(self, text: str) -> int:
        return 5

    def count_tokens_batch(self, texts: List[str]) -> List[int]:
        return [self.count_tokens(text) for text in texts]

    def similarity(self, u: "np.ndarray", v: "np.ndarray") -> float:
        return cosine_similarity(u.reshape(1, -1), v.reshape(1, -1))[0][0]

    @property
    def dimension(self) -> int:
        return 2


EmbeddingsRegistry.register(
    "customembedder",
    CustomEmebeddings,
)

chunker = SemanticChunker(
    embedding_model="customembedder",
    chunk_size=2,
    similarity_threshold=0.5,
)
```
It should raise the` ValueError: Tokenizer backend not supported` issue

**Comment by EvanSong77** [comment]
I also encountered the same problem

**Comment by bhavnicksm** [comment]
Hey @EvanSong77! 🙌

Could you pass me a sample for reproducing your issue? The tokenizers are currently passing the test mentioned above, so it might be a case I haven't tested for yet.

Thanks 😊

**Comment by bhavnicksm** [comment]
If you're facing a similar issue, here's a example, 

```python
from typing import List
import numpy as np
from chonkie import SemanticChunker
from chonkie.embeddings import BaseEmbeddings
from chonkie.embeddings.registry import EmbeddingsRegistry
from sklearn.metrics.pairwise import cosine_similarity

class CustomEmebeddings(BaseEmbeddings):
    def __init__(self, model_name: str):
        super().__init__()
        self.model_name = model_name

    def embed(self, text: str) -> "np.ndarray":
        return np.array([1.0, 2.0])

    def embed_batch(self, texts: List[str]) -> List["np.ndarray"]:
        return [self.embed(text) for text in texts]

    def count_tokens(self, text: str) -> int:
        return 5

    def count_tokens_batch(self, texts: List[str]) -> List[int]:
        return [self.count_tokens(text) for text in texts]

    def similarity(self, u: "np.ndarray", v: "np.ndarray") -> float:
        return cosine_similarity(u.reshape(1, -1), v.reshape(1, -1))[0][0]

    def get_tokenizer_or_token_counter(self):
        def _split(text):
            return len(text.split())
        return _split

    @property
    def dimension(self) -> int:
        return 2

emb = CustomEmebeddings("customembedder")

chunker = SemanticChunker(
    embedding_model=emb,
    chunk_size=2,
    similarity_threshold=0.5,
)
```

Something like this should work

Thanks! ☺️

**Comment by rsharma-autessa** [comment]
Btw @EvanSong77 if you're having the issue and you're overriding 
```
    def get_tokenizer_or_token_counter(self):
        def _split(text):
            return len(text.split())
        return _split
```

Remember that now the check is `isfunction` and not `ismethod` for tokenizers if you are using with SemanticChunker. So if you are using count_tokens or something as a lambda call instead (ex. a method), ex
```
    def get_tokenizer_or_token_counter(self):
        return lambda text: self.count_tokens(text)
```

It may be a good idea to update this method too since that's the expectation for the chunkers as the default
https://github.com/chonkie-ai/chonkie/blob/main/src/chonkie/embeddings/base.py#L139-L156

But tbh all this is lowkey, thank you so much for the library again and for addressing this so quickly!
