### ISSUE TITLE
How to set "trust_remote_code=True" for SentenceTransformerEmbedding?

### ISSUE THREAD

**Issue by anhhct** [chonkie-ai/chonkie#85]
I'm trying to use SemanticChunker, but its constructor doesn't have the option of sending extra kwarg to the embedding model, which is required when I want to use it with SentenceTransformer models from HunggingFace.
How could I do that?

**Comment by bhavnicksm** [comment]
Hey @anhhct, 

I am assuming you are trying to directly pass certain kwrargs to the `SemanticChunker` at the moment, which I would add in a patch, but as a work around, I'd suggest loading the `SentenceTransformerEmbeddings` seperately and load via `trust_remote_code=True` in the following way: 

<img width="1334" alt="image" src="https://github.com/user-attachments/assets/31bec709-9aec-49b9-9138-ef7869c6c013" />


I'll add the patch to pass kwargs directly from the `SemanticChunker` in the latest version. 

Thanks!

**Comment by bhavnicksm** [comment]
Hey @anhhct!

The fix is part of the source in chonkie with PR #96, you can now pass `trust_remote_code` directly to the `SemanticChunker` and expect it to work~!

Thanks 😊
